"""Generate the ``_index.md`` navigation hierarchy.

Corpus2Skill (arXiv 2604.14572) is the design: the hierarchy *is* the retrieval interface.
Navigation files stay small and every entry carries a one-line summary, so an agent picks a
branch without opening a single document. Three levels:

* root — names every folder holding documents
* folder — groups, each with its distinctive terms and a link to its own index
* group — the documents themselves

A folder at or below ``INLINE_MAX`` documents lists them inline; above that it explodes into
child indexes, which is what stops one folder index becoming a wall of text nobody reads.
"""

from __future__ import annotations

import datetime
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

from marketing_os.core.atomic import atomic_write
from marketing_os.core.catalog import build_catalog, coverage, load_catalog
from marketing_os.core.related import build_tfidf
from marketing_os.core.results import envelope, finding, next_action
from marketing_os.core.schema import load_schema

GENERATED = "Generated by `mos index sync` — do not hand-edit."

HUB_MIN_DOCS = 2
"""A folder with fewer documents than this is not worth its own index."""

INLINE_MAX = 40
"""At or below this many documents a folder lists them inline; above it, it explodes."""

GROUP_TERMS = 6
"""Distinctive terms shown per group, so a branch can be chosen without opening it."""

GLOBAL_MIN_DOCS = 25
"""Below this many documents in total, only the root index is worth generating."""

NAV_NAMES = ("_index.md", "_log.md")
LAST_UPDATED = re.compile(r"(?m)^last_updated:.*$")


def _exempt_names() -> frozenset[str]:
    return frozenset(load_schema()["frontmatter_contract"]["exempt_names"])


def discover_folders(docs: dict[str, dict[str, Any]]) -> list[str]:
    """Every top-level folder holding documents, biggest first.

    Discovered rather than configured, so a folder added next month is mapped without
    anyone remembering to update a list.
    """
    counts: Counter = Counter()
    for relative in docs:
        parts = relative.split("/")
        if len(parts) > 1 and Path(relative).name not in NAV_NAMES:
            counts[parts[0]] += 1
    return [folder for folder, count in counts.most_common() if count >= HUB_MIN_DOCS]


def _group_of(relative: str, folder: str) -> str:
    parent = Path(relative).parent.as_posix()
    return "" if parent == folder else parent[len(folder) + 1 :]


def _group_terms(
    rows: list[tuple[str, dict[str, Any]]],
    frequencies: dict[str, Counter],
    idf: dict[str, float],
) -> list[str]:
    aggregate: Counter = Counter()
    for relative, _doc in rows:
        for term, count in frequencies.get(relative, Counter()).items():
            aggregate[term] += min(count, 2) * idf.get(term, 0.0)
    return [term for term, _weight in aggregate.most_common(GROUP_TERMS)]


def _doc_lines(rows: list[tuple[str, dict[str, Any]]]) -> list[str]:
    lines: list[str] = []
    for relative, doc in sorted(rows, key=lambda row: row[0]):
        description = str(doc.get("description", "")).strip().replace("\n", " ")[:140]
        target = relative[:-3]
        lines.append(f"- [[{target}]] — {description}" if description else f"- [[{target}]]")
    return lines


def _frontmatter(title: str, description: str, today: str, pages: int | None = None) -> list[str]:
    lines = ["---", f"title: {title}", f"description: {description}", "type: reference"]
    if pages is not None:
        lines.append(f"pages: {pages}")
    lines.extend([f"last_updated: {today}", "status: active", "---", ""])
    return lines


def folder_index_text(
    folder: str,
    docs: dict[str, dict[str, Any]],
    today: str,
    frequencies: dict[str, Counter],
    idf: dict[str, float],
) -> tuple[str, int, dict[str, list[tuple[str, dict[str, Any]]]], bool]:
    rows = [
        (relative, doc)
        for relative, doc in docs.items()
        if relative.startswith(folder + "/") and Path(relative).name not in NAV_NAMES
    ]
    if not rows:
        return "", 0, {}, False

    direct = [(relative, doc) for relative, doc in rows if not _group_of(relative, folder)]
    groups: dict[str, list[tuple[str, dict[str, Any]]]] = defaultdict(list)
    for relative, doc in rows:
        group = _group_of(relative, folder)
        if group:
            groups[group.split("/")[0]].append((relative, doc))

    explode = len(rows) > INLINE_MAX and bool(groups)
    plural = "s" if len(rows) != 1 else ""
    description = (
        f"Routing map for {folder}/ — {len(rows)} document{plural}"
        + (f" across {len(groups)} group{'s' if len(groups) != 1 else ''}" if groups else "")
        + ". Each entry carries a one-line summary so a branch can be chosen without "
        "opening the files."
    )
    lines = _frontmatter(f"{folder} index", description, today, pages=len(rows))
    lines += [f"# {folder}/ — index", "", f"*{GENERATED}*", ""]

    if explode:
        lines += ["## Groups", "", "| group | documents | covers |", "| --- | --- | --- |"]
        for group in sorted(groups):
            terms = ", ".join(_group_terms(groups[group], frequencies, idf))
            lines.append(
                f"| [[{folder}/{group}/_index|{group}/]] | {len(groups[group])} | {terms} |"
            )
        lines.append("")
        if direct:
            lines += [f"## Loose documents in {Path(folder).name}/", ""] + _doc_lines(direct) + [""]
    else:
        for group in sorted(groups) + ([""] if direct else []):
            rows_in_group = groups[group] if group else direct
            lines += [f"## {group or '(top level)'}", ""] + _doc_lines(rows_in_group) + [""]

    return "\n".join(lines).rstrip() + "\n", len(rows), dict(groups), explode


def root_index_text(root_name: str, today: str, folder_counts: dict[str, int], total: int) -> str:
    description = (
        "Top of the navigation hierarchy — start here. Names every main folder, what it "
        "holds, and the questions it answers, so an agent can route in one hop."
    )
    lines = _frontmatter(f"{root_name} index", description, today, pages=total)
    lines += [
        f"# {root_name} — index",
        "",
        f"*{GENERATED}*",
        "",
        "Start here. Navigate down the hierarchy rather than searching blind. Each folder "
        "below with its own `_index.md` lists every document with a one-line description.",
        "",
        "## Folders",
        "",
    ]
    for folder, count in folder_counts.items():
        if not count:
            continue
        lines.append(
            f"- [[{folder}/_index|{folder}/]] — {count} document{'s' if count != 1 else ''}"
        )
    lines += [
        "",
        "## Conventions",
        "",
        "- Every document carries the frontmatter block in `CONTRACT.md` (`title`, `type`, "
        "`description`, `date`, `status`, plus `sources`, `related`, or `produced_by`).",
        "- Substantial documents end with a `## Related` block; those cross-folder links are "
        "what make the brain navigable rather than merely tidy.",
        "- `mos index build .` then `mos index sync . --yes` regenerates this map.",
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


def _plan_write(
    root: Path, relative: str, text: str, entries: int
) -> tuple[dict[str, Any] | None, dict[str, str] | None]:
    """Decide whether a generated file may be written over what is already on disk."""
    target = root / relative
    if target.exists():
        try:
            existing = target.read_text(encoding="utf-8")
        except OSError:
            existing = ""
        if LAST_UPDATED.sub("", existing) == LAST_UPDATED.sub("", text):
            return None, None
        if GENERATED not in existing:
            return None, finding(
                "hand-written-index",
                "A hand-written index is here; the generator will not overwrite it.",
                severity="warning",
                path=relative,
            )
        return {"relative": relative, "text": text, "entries": entries, "action": "update"}, None
    return {"relative": relative, "text": text, "entries": entries, "action": "create"}, None


def plan_indexes(
    root: Path, docs: dict[str, dict[str, Any]], today: str
) -> tuple[list[dict[str, Any]], list[dict[str, str]]]:
    """Compute every index file this catalogue implies. Writes nothing."""
    frequencies, idf = build_tfidf(docs)
    writes: list[dict[str, Any]] = []
    findings: list[dict[str, str]] = []
    counts: dict[str, int] = {}

    countable = sum(1 for relative in docs if Path(relative).name not in NAV_NAMES)
    folders = discover_folders(docs) if countable >= GLOBAL_MIN_DOCS else []

    def emit(folder: str) -> int:
        text, entries, groups, explode = folder_index_text(folder, docs, today, frequencies, idf)
        if not entries:
            return 0
        write, problem = _plan_write(root, f"{folder}/_index.md", text, entries)
        if write:
            writes.append(write)
        if problem:
            findings.append(problem)
        if explode:
            for group in sorted(groups):
                emit(f"{folder}/{group}")
        return entries

    for folder in folders:
        counts[folder] = emit(folder)

    root_text = root_index_text(root.name, today, counts, countable)
    write, problem = _plan_write(root, "_index.md", root_text, len(counts))
    if write:
        writes.append(write)
    if problem:
        findings.append(problem)
    return writes, findings


def apply_indexes(root: Path, writes: list[dict[str, Any]]) -> list[str]:
    """Write each planned index, one whole file at a time.

    An index is generated, but it is still a document in the operator's repository and
    still the map an agent navigates by. ``atomic_write`` keeps a failed write from
    leaving a truncated one behind; the text is already LF-joined and is written as bytes,
    so the line endings do not change.
    """
    applied: list[str] = []
    for item in writes:
        atomic_write(root / item["relative"], item["text"])
        applied.append(item["relative"])
    return applied


def sync_repo(root: Path, *, apply: bool) -> dict[str, Any]:
    """``mos index sync`` — regenerate the navigation hierarchy from the live corpus."""
    root = root.expanduser().resolve()
    docs = build_catalog(root)
    today = datetime.date.today().isoformat()
    writes, findings = plan_indexes(root, docs, today)
    applied = apply_indexes(root, writes) if apply else []
    changes = [f"{item['action']} {item['relative']}" for item in writes]
    countable = sum(1 for relative in docs if Path(relative).name not in NAV_NAMES)
    if countable < GLOBAL_MIN_DOCS:
        findings.append(
            finding(
                "small-corpus",
                f"{countable} document(s) is below the {GLOBAL_MIN_DOCS}-document floor; only "
                "the root index is generated. A hierarchy over a near-empty brain is noise.",
                severity="warning",
            )
        )
    if writes and not apply:
        action = next_action("apply-index-sync", "Apply the reviewed index plan with `--yes`.")
    else:
        action = next_action("run-query", 'Navigate the brain with `mos query "<question>" .`.')
    return envelope(
        "index-sync",
        root,
        ok=True,
        changes=changes,
        findings=findings,
        action=action,
        applied=applied,
        planned=not apply,
        documents=countable,
    )


def status_repo(root: Path) -> dict[str, Any]:
    """``mos index status`` — catalogue freshness and navigation coverage."""
    root = root.expanduser().resolve()
    stored = load_catalog(root)
    live = build_catalog(root)
    stats = coverage(live)
    folders = discover_folders(live)
    present = [folder for folder in folders if (root / folder / "_index.md").is_file()]
    findings: list[dict[str, str]] = []
    if stored is None:
        findings.append(
            finding(
                "no-catalog",
                "No catalogue on disk; `mos query` falls back to reading every document.",
                severity="warning",
                path=".mos/local/catalog.json",
            )
        )
    elif stored != live:
        findings.append(
            finding(
                "stale-catalog",
                "The catalogue no longer matches the corpus. Run `mos index build .`.",
                severity="warning",
                path=".mos/local/catalog.json",
            )
        )
    total = max(stats["documents"], 1)
    return envelope(
        "index-status",
        root,
        ok=True,
        findings=findings,
        action=next_action(
            "rebuild-catalog" if findings else "run-query",
            "Refresh the catalogue and the index hierarchy."
            if findings
            else "The navigation layer is current.",
        ),
        coverage=stats,
        percent={
            "frontmatter": 100 * stats["with_frontmatter"] // total,
            "description": 100 * stats["with_description"] // total,
            "outgoing_links": 100 * stats["with_outgoing_links"] // total,
        },
        indexes={"expected": folders, "present": present},
        root_index=(root / "_index.md").is_file(),
    )
